### ISSUE TITLE
Opening many ports between applications is cumbersome

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry-incubator/cf-networking-release#7]
Thanks to Container Networking, it's possible to easy to run simple microservice architectures on Cloud Foundry, such as the "cats and dogs" example app.  It's even possible to run more sophisticated distributed systems such as Spark.  It's a bit cumbersome, but a desirable UX seems easily within reach with some minor tweaks to the API.

With Spark, the Master and Workers spin up and down many concurrent TCP listeners, on random ports (to deal with the large numbers and concurrency), and they need to be able to communicate with each other on those ports.  It would be nice to open up all ports, or a range of ports, with a single policy definition.  Right now, you can do this with the API but the request payload has tens of thousands of items in the array.  Through the `cf` CLI plugin, it's even worse, because you can only define one policy at a time, so you'd have to issue tens of thousands of individual commands.

My current workaround is [this ruby script](https://gist.github.com/Amit-PivotalLabs/7c86c92aae3123ac809e81795a41acfa#file-allow-access-rb) which takes 3-4 minutes to run.

/cc @rusha19 @jaydunk @rosenhouse @jbayer

**Comment by mcwumbly** [comment]
There is a [port-ranges epic](https://www.pivotaltracker.com/epic/show/3354119) in Tracker, if you want to peek at what where we are in our thinking on this topic.

Rather than just folding something like this ruby script into the CLI, adding real support for port ranges will not only improve the UX, but also address potential performance issues that could arise from having 1000s of separate iptables rules on each cell for enforcing these individual policies.  With native port range support, each range would be a single iptables rule.

As for your ruby script, we do similar things in some of our performance and scaling tests that create 1000's of policies (In this case, port ranges are not a solution).

We sometimes ran into issues since we wanted to test with arbitrarily large numbers of policies, so to get around this, we create [chunks of 1000 policies](https://github.com/cloudfoundry-incubator/cf-networking-release/blob/develop/src/test/perf/policy-server/main.go#L109-L116) per request.

**Comment by rusha19** [comment]
cf-networking-release v0.14.0 supports port-ranges in policy commands.
